import '../contents/data_content.dart';
import 'speech_to_text_client.dart';
import 'speech_to_text_options.dart';
import 'speech_to_text_response.dart';
import 'speech_to_text_response_update.dart';

/// Extensions for [SpeechToTextClient].
extension SpeechToTextClientExtensions on SpeechToTextClient {
  /// Asks the [SpeechToTextClient] for an object of type `TService`.
///
/// Remarks: The purpose of this method is to allow for the retrieval of
/// strongly typed services that may be provided by the [SpeechToTextClient],
/// including itself or any services it might be wrapping.
///
/// Returns: The found object, otherwise `null`.
///
/// [client] The client.
///
/// [serviceKey] An optional key that can be used to help identify the target
/// service.
///
/// [TService] The type of the object to be retrieved.
TService? getService<TService>({Object? serviceKey}) {
_ = Throw.ifNull(client);
return (TService?)client.getService(typeof(TService), serviceKey);
 }
/// Generates text from speech providing a single audio speech [DataContent].
///
/// Returns: The text generated by the client.
///
/// [client] The client.
///
/// [audioSpeechContent] The single audio speech content.
///
/// [options] The speech to text options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Future<SpeechToTextResponse> getText(
  DataContent audioSpeechContent,
  {SpeechToTextOptions? options, CancellationToken? cancellationToken, },
) {
_ = Throw.ifNull(client);
_ = Throw.ifNull(audioSpeechContent);
var audioSpeechStream = MemoryMarshal.tryGetArray(audioSpeechContent.data, out var array) ?
            memoryStream(array.array!, array.offset, array.count) :
            memoryStream(audioSpeechContent.data.toArray());
return client.getTextAsync(audioSpeechStream, options, cancellationToken);
 }
/// Generates text from speech providing a single audio speech [DataContent].
///
/// Returns: The text generated by the client.
///
/// [client] The client.
///
/// [audioSpeechContent] The single audio speech content.
///
/// [options] The speech to text options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Stream<SpeechToTextResponseUpdate> getStreamingText(
  DataContent audioSpeechContent,
  {SpeechToTextOptions? options, CancellationToken? cancellationToken, },
) {
_ = Throw.ifNull(client);
_ = Throw.ifNull(audioSpeechContent);
var audioSpeechStream = MemoryMarshal.tryGetArray(audioSpeechContent.data, out var array) ?
            memoryStream(array.array!, array.offset, array.count) :
            memoryStream(audioSpeechContent.data.toArray());
return client.getStreamingTextAsync(audioSpeechStream, options, cancellationToken);
 }
 }
