import 'package:extensions/annotations.dart';

import '../../system/async_disposable.dart';
import '../../system/threading/cancellation_token.dart';
import 'realtime_client_message.dart';
import 'realtime_server_message.dart';
import 'realtime_session_options.dart';

/// Represents a real-time session.
///
/// Provides methods to manage a real-time session and to interact with the
/// real-time model.
///
/// This is an experimental feature.
@Source(
  name: 'IRealtimeClientSession.cs',
  namespace: 'Microsoft.Extensions.AI',
  repository: 'dotnet/extensions',
  path: 'src/Libraries/Microsoft.Extensions.AI.Abstractions/Realtime/',
  commit: '2e537166e4231e50cceb66832b9dfd1382e24d1b',
)
abstract class RealtimeClientSession implements AsyncDisposable {
  /// The current session options.
  RealtimeSessionOptions? get options;

  /// Sends a client [message] to the session.
  ///
  /// This may be called concurrently from multiple sources. Provider
  /// implementations must serialize access to the underlying transport when it
  /// does not support concurrent sends.
  Future<void> send(
    RealtimeClientMessage message, {
    CancellationToken? cancellationToken,
  });

  /// Streams the response messages generated by the session.
  ///
  /// This cannot be called multiple times concurrently on the same session
  /// instance.
  Stream<RealtimeServerMessage> getStreamingResponse({
    CancellationToken? cancellationToken,
  });

  /// Asks the session for an object of the specified type [T].
  ///
  /// Returns the found object, or `null` if no matching service is available.
  T? getService<T>({Object? key});
}
