/// Represents the role of a chat message author.
class ChatRole {
  /// Creates a new [ChatRole] with the given [value].
  const ChatRole(this.value);

  /// The role value.
  final String value;

  /// The system role, used for providing instructions to the model.
  static const ChatRole system = ChatRole('system');

  /// The assistant role, used for messages generated by the model.
  static const ChatRole assistant = ChatRole('assistant');

  /// The user role, used for messages sent by the user.
  static const ChatRole user = ChatRole('user');

  /// The tool role, used for messages containing tool/function results.
  static const ChatRole tool = ChatRole('tool');

  @override
  bool operator ==(Object other) =>
      other is ChatRole &&
      value.toLowerCase() == other.value.toLowerCase();

  @override
  int get hashCode => value.toLowerCase().hashCode;

  @override
  String toString() => value;
}
