/// Represents an embedding generated by a [EmbeddingGenerator].
///
/// Remarks: This base class provides metadata about the embedding. Derived
/// types provide the concrete data contained in the embedding.
class Embedding {
  /// Initializes a new instance of the [Embedding] class.
  const Embedding();

  /// Gets or sets a timestamp at which the embedding was created.
  DateTime? createdAt;

  /// Gets the dimensionality of the embedding vector.
  ///
  /// Remarks: This value corresponds to the number of elements in the embedding
  /// vector.
  final int dimensions;

  /// Gets or sets the model ID using in the creation of the embedding.
  String? modelId;

  /// Gets or sets any additional properties associated with the embedding.
  AdditionalPropertiesDictionary? additionalProperties;
}
