import 'package:extensions/annotations.dart';

/// Marks a property on a record as the key field in a vector store collection.
///
/// Exactly one property per record class must be annotated with
/// [VectorStoreKeyAttribute].
///
/// Example:
/// ```dart
/// class Hotel {
///   @VectorStoreKeyAttribute()
///   final String hotelId;
///
///   Hotel({required this.hotelId});
/// }
/// ```
///
/// Since Dart has no built-in runtime reflection, annotations are intended for
/// use with code generators or explicit [VectorStoreCollectionDefinition]
/// construction.
@Source(
  name: 'VectorStoreKeyAttribute.cs',
  namespace: 'Microsoft.Extensions.VectorData',
  repository: 'dotnet/extensions',
  path:
      'src/Libraries/Microsoft.Extensions.VectorData.Abstractions/VectorData/Attributes/',
)
final class VectorStoreKeyAttribute {
  /// Creates a [VectorStoreKeyAttribute].
  const VectorStoreKeyAttribute({this.storageName, this.isAutoGenerated});

  /// The name used when storing this property in the vector store.
  ///
  /// Defaults to the annotated property name when null.
  final String? storageName;

  /// Whether the key is automatically generated by the vector store.
  ///
  /// When true, providers may omit the key during upsert and let the store
  /// assign a value.
  final bool? isAutoGenerated;
}
