import 'package:extensions/annotations.dart';

import '../../ai/embeddings/embedding_generator.dart';
import '../record_definition/vector_store_collection_definition.dart';
import '../record_definition/vector_store_data_property.dart';
import '../record_definition/vector_store_key_property.dart';
import '../record_definition/vector_store_property.dart';
import '../record_definition/vector_store_vector_property.dart';
import 'collection_model.dart';
import 'collection_model_building_options.dart';
import 'data_property_model.dart';
import 'embedding_generation_dispatcher.dart';
import 'key_property_model.dart';
import 'property_model.dart';
import 'vector_data_strings.dart';
import 'vector_property_model.dart';

/// Builds a [CollectionModel] from a [VectorStoreCollectionDefinition].
///
/// Subclass this and implement [isDataPropertyTypeValid] and
/// [isVectorPropertyTypeValid] for each provider. Override [customize] to
/// adjust the model after property processing, and [validate] / [validateProperty]
/// to add provider-specific validation rules.
///
/// This is a support type for provider implementors; application code should
/// not reference it directly.
@Source(
  name: 'CollectionModelBuilder.cs',
  namespace: 'Microsoft.Extensions.VectorData.ProviderServices',
  repository: 'dotnet/extensions',
  path:
      'src/Libraries/Microsoft.Extensions.VectorData.Abstractions/'
      'ProviderServices/',
)
abstract class CollectionModelBuilder {
  /// Creates a [CollectionModelBuilder] with the given [options].
  CollectionModelBuilder(this.options);

  /// The options controlling model construction.
  final CollectionModelBuildingOptions options;

  /// The key properties accumulated during [processProperty].
  final List<KeyPropertyModel> keyProperties = [];

  /// The data properties accumulated during [processProperty].
  final List<DataPropertyModel> dataProperties = [];

  /// The vector properties accumulated during [processProperty].
  final List<VectorPropertyModel> vectorProperties = [];

  /// All properties, indexed by their model name.
  final Map<String, PropertyModel> propertyMap = {};

  EmbeddingGenerator? _defaultEmbeddingGenerator;

  /// All properties of all types.
  Iterable<PropertyModel> get properties => propertyMap.values;

  /// The dispatchers used to resolve embedding types and generate embeddings.
  ///
  /// Override to add provider-specific embedding types. The first dispatcher
  /// whose [EmbeddingGenerationDispatcher.resolveEmbeddingType] returns
  /// non-null wins.
  List<EmbeddingGenerationDispatcher> get embeddingGenerationDispatchers =>
      [EmbeddingGenerationDispatcher.createDefault()];

  /// Builds a [CollectionModel] for dynamic record mapping (using
  /// `Map<String, Object?>` records) from [definition].
  ///
  /// [defaultEmbeddingGenerator] is used for vector properties that do not
  /// configure their own generator.
  CollectionModel buildDynamic(
    VectorStoreCollectionDefinition definition, {
    EmbeddingGenerator? defaultEmbeddingGenerator,
  }) {
    _defaultEmbeddingGenerator = defaultEmbeddingGenerator;

    for (final defProp in definition.properties) {
      processProperty(defProp);
    }

    customize();
    validate(definition);

    for (final property in propertyMap.values) {
      property.configureDynamicAccessors();
    }

    return CollectionModel(
      recordFactory: () => <String, Object?>{},
      keyProperties: keyProperties,
      dataProperties: dataProperties,
      vectorProperties: vectorProperties,
      propertyMap: propertyMap,
    );
  }

  /// Processes a single property from the definition, creating the
  /// appropriate [PropertyModel] subtype and adding it to the property lists.
  ///
  /// Override to handle provider-specific property configuration. Call
  /// `super.processProperty(definitionProperty)` before or after custom logic.
  void processProperty(VectorStoreProperty definitionProperty) {
    final propertyName = definitionProperty.propertyName;
    PropertyModel property;

    if (definitionProperty is VectorStoreKeyProperty) {
      final keyProp = KeyPropertyModel(
        modelName: propertyName,
        type: Object,
      );
      keyProp.isAutoGenerated = supportsKeyAutoGeneration(keyProp.type);
      keyProperties.add(keyProp);
      property = keyProp;
    } else if (definitionProperty is VectorStoreDataProperty) {
      final dataProp = DataPropertyModel(
        modelName: propertyName,
        type: Object,
      );
      dataProp.isIndexed = definitionProperty.isIndexed;
      dataProp.isFullTextIndexed = definitionProperty.isFullTextIndexed;
      dataProperties.add(dataProp);
      property = dataProp;
    } else if (definitionProperty is VectorStoreVectorProperty) {
      final vecProp = VectorPropertyModel(
        modelName: propertyName,
        type: Object,
      );
      if (definitionProperty.dimensions != null) {
        vecProp.dimensions = definitionProperty.dimensions!;
      }
      vecProp.indexKind = definitionProperty.indexKind;
      vecProp.distanceFunction = definitionProperty.distanceFunction;

      _configureVectorPropertyEmbedding(
        vecProp,
        _defaultEmbeddingGenerator,
        definitionProperty.embeddingType,
      );

      vectorProperties.add(vecProp);
      property = vecProp;
    } else {
      throw StateError(
        'Unknown property definition type: ${definitionProperty.runtimeType}',
      );
    }

    _setPropertyStorageName(property, definitionProperty.storageName);

    propertyMap[propertyName] = property;
  }

  void _setPropertyStorageName(PropertyModel property, String? storageName) {
    if (property is KeyPropertyModel &&
        options.reservedKeyStorageName != null) {
      property.storageName = options.reservedKeyStorageName!;
      return;
    }

    if (storageName == null) return;

    if (options.usesExternalSerializer) return;

    property.storageName = storageName;
  }

  void _configureVectorPropertyEmbedding(
    VectorPropertyModel vectorProperty,
    EmbeddingGenerator? embeddingGenerator,
    Type? userRequestedEmbeddingType,
  ) {
    vectorProperty.embeddingGenerator = embeddingGenerator;

    String? supportedTypes;
    if (isVectorPropertyTypeValid(vectorProperty.type,
        supportedTypes: supportedTypes)) {
      vectorProperty.embeddingType = vectorProperty.type;
      if (embeddingGenerator != null) {
        vectorProperty.embeddingGenerationDispatcher =
            _resolveSearchOnlyDispatcher(vectorProperty, embeddingGenerator);
      }
    } else if (embeddingGenerator != null) {
      final (embeddingType, dispatcher) = _resolveEmbeddingType(
        vectorProperty,
        embeddingGenerator,
        userRequestedEmbeddingType,
      );
      vectorProperty.embeddingType = embeddingType;
      vectorProperty.embeddingGenerationDispatcher = dispatcher;
    }
  }

  (Type?, EmbeddingGenerationDispatcher?) _resolveEmbeddingType(
    VectorPropertyModel vectorProperty,
    EmbeddingGenerator embeddingGenerator,
    Type? userRequestedEmbeddingType,
  ) {
    for (final dispatcher in embeddingGenerationDispatchers) {
      final resolved = dispatcher.resolveEmbeddingType(
        vectorProperty,
        embeddingGenerator,
        userRequestedEmbeddingType,
      );
      if (resolved != null) return (resolved, dispatcher);
    }
    return (null, null);
  }

  EmbeddingGenerationDispatcher? _resolveSearchOnlyDispatcher(
    VectorPropertyModel vectorProperty,
    EmbeddingGenerator embeddingGenerator,
  ) {
    for (final dispatcher in embeddingGenerationDispatchers) {
      if (dispatcher.canGenerateEmbedding(vectorProperty, embeddingGenerator)) {
        return dispatcher;
      }
    }
    return null;
  }

  /// Override to perform provider-specific model adjustments after all
  /// properties have been processed and before validation.
  void customize() {}

  /// Validates the fully built model.
  ///
  /// Throws [StateError] for structural constraint violations (key count,
  /// vector count, duplicate storage names). Override to add
  /// provider-specific checks; call `super.validate(definition)`.
  void validate(VectorStoreCollectionDefinition? definition) {
    if (keyProperties.length > 1) {
      throw StateError(
        'Multiple key properties found in the provided '
        'VectorStoreCollectionDefinition while only one is supported.',
      );
    }

    if (keyProperties.isEmpty) {
      throw StateError(
        'No key property found in the provided '
        'VectorStoreCollectionDefinition while at least one is required.',
      );
    }

    if (options.requiresAtLeastOneVector && vectorProperties.isEmpty) {
      throw StateError(
        'No vector property found in the provided '
        'VectorStoreCollectionDefinition while at least one is required.',
      );
    }

    if (!options.supportsMultipleVectors && vectorProperties.length > 1) {
      throw StateError(
        'Multiple vector properties found in the provided '
        'VectorStoreCollectionDefinition while only one is supported.',
      );
    }

    final storageNameMap = <String, PropertyModel>{};
    for (final property in propertyMap.values) {
      validateProperty(property, definition);

      final existing = storageNameMap[property.storageName];
      if (existing != null) {
        throw StateError(
          "Property '${property.modelName}' is being mapped to storage name "
          "'${property.storageName}', but property '${existing.modelName}' "
          'is already mapped to the same storage name.',
        );
      }
      storageNameMap[property.storageName] = property;
    }
  }

  /// Validates a single [propertyModel].
  ///
  /// Override to add provider-specific validation. Call
  /// `super.validateProperty(propertyModel, definition)` to retain the base
  /// checks.
  void validateProperty(
    PropertyModel propertyModel,
    VectorStoreCollectionDefinition? definition,
  ) {
    switch (propertyModel) {
      case KeyPropertyModel keyProperty:
        if (keyProperty.isAutoGenerated &&
            !supportsKeyAutoGeneration(keyProperty.type)) {
          throw StateError(
            "Property '${keyProperty.modelName}' is configured for "
            'auto-generation, but key properties of type '
            "'${keyProperty.type}' do not support auto-generation.",
          );
        }

      case DataPropertyModel dataProperty:
        String? supportedTypes;
        if (!isDataPropertyTypeValid(dataProperty.type,
            supportedTypes: supportedTypes)) {
          throw StateError(
            "Property '${dataProperty.modelName}' has unsupported type "
            "'${dataProperty.type}'. Data properties must be one of the "
            'supported types: $supportedTypes.',
          );
        }

      case VectorPropertyModel vectorProperty:
        if (vectorProperty.embeddingType == null) {
          String? supportedVectorTypes;
          if (isVectorPropertyTypeValid(vectorProperty.type,
              supportedTypes: supportedVectorTypes)) {
            throw StateError(
              "EmbeddingType cannot be null when the property type is "
              'supported. This is a bug in the provider.',
            );
          }

          if (vectorProperty.embeddingGenerator == null) {
            throw StateError(
              VectorDataStrings.embeddingGeneratorWithInvalidEmbeddingType(
                vectorProperty,
              ),
            );
          }

          final userRequestedEmbeddingType = definition?.properties
              .whereType<VectorStoreVectorProperty>()
              .where((p) => p.propertyName == vectorProperty.modelName)
              .map((p) => p.embeddingType)
              .firstOrNull;

          if (userRequestedEmbeddingType != null) {
            throw StateError(
              isVectorPropertyTypeValid(userRequestedEmbeddingType,
                      supportedTypes: supportedVectorTypes)
                  ? VectorDataStrings
                      .configuredEmbeddingTypeIsUnsupportedByTheGenerator(
                      vectorProperty,
                      userRequestedEmbeddingType,
                    )
                  : VectorDataStrings
                      .configuredEmbeddingTypeIsUnsupportedByTheProvider(
                      vectorProperty,
                      userRequestedEmbeddingType,
                      supportedVectorTypes ?? 'none',
                    ),
            );
          }

          throw StateError(
            VectorDataStrings.incompatibleEmbeddingGenerator(
              vectorProperty,
              vectorProperty.embeddingGenerator!,
              supportedVectorTypes ?? 'none',
            ),
          );
        }

        String? supportedVectorTypes2;
        if (!isVectorPropertyTypeValid(vectorProperty.embeddingType!,
            supportedTypes: supportedVectorTypes2)) {
          throw StateError(
            "Property '${vectorProperty.modelName}' has unsupported embedding "
            "type '${vectorProperty.embeddingType}'. Vector properties must "
            'be one of the supported types: $supportedVectorTypes2.',
          );
        }

        if (vectorProperty.dimensions <= 0) {
          throw StateError(
            "Vector property '${vectorProperty.modelName}' must have a "
            'positive number of dimensions.',
          );
        }
    }
  }

  /// Returns whether the given [keyPropertyType] supports auto-generation.
  ///
  /// The default returns `false`. Override to support auto-generated keys.
  bool supportsKeyAutoGeneration(Type keyPropertyType) => false;

  /// Returns whether [type] is a valid type for a data property.
  ///
  /// When returning `false`, set [supportedTypes] to a human-readable list of
  /// the valid types (used in error messages).
  bool isDataPropertyTypeValid(Type type, {String? supportedTypes});

  /// Returns whether [type] is a valid type for a vector property.
  ///
  /// When returning `false`, set [supportedTypes] to a human-readable list of
  /// the valid types (used in error messages).
  bool isVectorPropertyTypeValid(Type type, {String? supportedTypes});
}
