import 'package:extensions/annotations.dart';

import 'property_model.dart';

/// Represents a key property on a vector store record.
///
/// This is a support type for provider implementors; application code should
/// not reference it directly.
@Source(
  name: 'KeyPropertyModel.cs',
  namespace: 'Microsoft.Extensions.VectorData.ProviderServices',
  repository: 'dotnet/extensions',
  path:
      'src/Libraries/Microsoft.Extensions.VectorData.Abstractions/'
      'ProviderServices/',
)
class KeyPropertyModel extends PropertyModel {
  /// Creates a [KeyPropertyModel] with the given [modelName] and [type].
  KeyPropertyModel({
    required super.modelName,
    required super.type,
    super.isNullable,
  });

  /// Whether this key property's value is auto-generated by the store.
  bool isAutoGenerated = false;

  /// The serialized name the external serializer produces for this key.
  ///
  /// Needed by providers that use an external JSON serializer combined with
  /// a reserved key storage name (e.g. CosmosDB uses `"id"`).
  String? serializedKeyName;

  @override
  String toString() =>
      '$modelName (Key, $type'
      '${isAutoGenerated ? ', auto-generated' : ''})';
}
