import '../contents/ai_content.dart';
import '../contents/data_content.dart';
import 'image_generation_options.dart';
import 'image_generation_request.dart';
import 'image_generation_response.dart';
import 'image_generator.dart';

/// Provides extension methods for [ImageGenerator].
extension ImageGeneratorExtensions on ImageGenerator {
  /// Asks the [ImageGenerator] for an object of type `TService`.
///
/// Remarks: The purpose of this method is to allow for the retrieval of
/// strongly typed services that may be provided by the [ImageGenerator],
/// including itself or any services it might be wrapping.
///
/// Returns: The found object, otherwise `null`.
///
/// [generator] The generator.
///
/// [serviceKey] An optional key that can be used to help identify the target
/// service.
///
/// [TService] The type of the object to be retrieved.
TService? getService<TService>({Object? serviceKey}) {
_ = Throw.ifNull(generator);
return generator.getService(typeof(TService), serviceKey) is TService service ? service : default;
 }
/// Asks the [ImageGenerator] for an object of the specified type
/// `serviceType` and throws an exception if one isn't available.
///
/// Remarks: The purpose of this method is to allow for the retrieval of
/// services that are required to be provided by the [ImageGenerator],
/// including itself or any services it might be wrapping.
///
/// Returns: The found object.
///
/// [generator] The generator.
///
/// [serviceType] The type of object being requested.
///
/// [serviceKey] An optional key that can be used to help identify the target
/// service.
Object getRequiredService(Object? serviceKey, {Type? serviceType, }) {
_ = Throw.ifNull(generator);
_ = Throw.ifNull(serviceType);
return generator.getService(serviceType, serviceKey) ??
            throw Throw.createMissingServiceException(serviceType, serviceKey);
 }
/// Generates images based on a text prompt.
///
/// Returns: The images generated by the generator.
///
/// [generator] The image generator.
///
/// [prompt] The prompt to guide the image generation.
///
/// [options] The image generation options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Future<ImageGenerationResponse> generateImages(
  String prompt,
  {ImageGenerationOptions? options, CancellationToken? cancellationToken, },
) {
_ = Throw.ifNull(generator);
_ = Throw.ifNull(prompt);
return generator.generateAsync(imageGenerationRequest(prompt), options, cancellationToken);
 }
/// Edits images based on original images and a text prompt.
///
/// Returns: The images generated by the generator.
///
/// [generator] The image generator.
///
/// [originalImages] The images to base edits on.
///
/// [prompt] The prompt to guide the image editing.
///
/// [options] The image generation options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Future<ImageGenerationResponse> editImages(
  Iterable<AContent> originalImages,
  String prompt,
  {ImageGenerationOptions? options, CancellationToken? cancellationToken, },
) {
_ = Throw.ifNull(generator);
_ = Throw.ifNull(originalImages);
_ = Throw.ifNull(prompt);
return generator.generateAsync(
  imageGenerationRequest(prompt, originalImages),
  options,
  cancellationToken,
);
 }
/// Edits a single image based on the original image and the specified prompt.
///
/// Returns: The images generated by the generator.
///
/// [generator] The image generator.
///
/// [originalImage] The single image to base edits on.
///
/// [prompt] The prompt to guide the image generation.
///
/// [options] The image generation options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Future<ImageGenerationResponse> editImage(
  String prompt,
  ImageGenerationOptions? options,
  CancellationToken cancellationToken,
  {DataContent? originalImage, ReadOnlyMemory<int>? originalImageData, String? fileName, },
) {
_ = Throw.ifNull(generator);
_ = Throw.ifNull(originalImage);
_ = Throw.ifNull(prompt);
return generator.generateAsync(
  imageGenerationRequest(prompt, [originalImage]),
  options,
  cancellationToken,
);
 }
 }
