import 'image_generation_options.dart';
import 'image_generation_request.dart';
import 'image_generation_response.dart';

/// Represents a generator of images.
abstract class ImageGenerator implements Disposable {
  /// Sends an image generation request and returns the generated image as a
  /// [ImageGenerationResponse].
  ///
  /// Returns: The images generated by the [ImageGenerationRequest].
  ///
  /// [request] The image generation request containing the prompt and optional
  /// original images for editing.
  ///
  /// [options] The image generation options to configure the request.
  ///
  /// [cancellationToken] The [CancellationToken] to monitor for cancellation
  /// requests. The default is [None].
  Future<ImageGenerationResponse> generate(
    ImageGenerationRequest request, {
    ImageGenerationOptions? options,
    CancellationToken? cancellationToken,
  });

  /// Asks the [ImageGenerator] for an object of the specified type
  /// `serviceType`.
  ///
  /// Remarks: The purpose of this method is to allow for the retrieval of
  /// strongly typed services that might be provided by the [ImageGenerator],
  /// including itself or any services it might be wrapping.
  ///
  /// Returns: The found object, otherwise `null`.
  ///
  /// [serviceType] The type of object being requested.
  ///
  /// [serviceKey] An optional key that can be used to help identify the target
  /// service.
  Object? getService(Type serviceType, {Object? serviceKey});
}
