import '../abstractions/chat_completion/chat_client.dart';
import '../abstractions/chat_completion/chat_message.dart';
import '../abstractions/chat_completion/chat_options.dart';
import '../abstractions/chat_completion/chat_response_format.dart';

/// Provides extension methods on [ChatClient] that simplify working with
/// structured output.
extension ChatClientStructuredOutputExtensions on ChatClient {
  /// Sends chat messages, requesting a response matching the type `T`.
  ///
  /// Returns: The response messages generated by the client.
  ///
  /// [chatClient] The [ChatClient].
  ///
  /// [messages] The chat content to send.
  ///
  /// [options] The chat options to configure the request.
  ///
  /// [useJsonSchemaResponseFormat] `true` to set a JSON schema on the
  /// [ChatResponseFormat]; otherwise, `false`. The default is `true`. Using a
  /// JSON schema improves reliability if the underlying model supports native
  /// structured output with a schema, but might cause an error if the model
  /// does not support it.
  ///
  /// [cancellationToken] The [CancellationToken] to monitor for cancellation
  /// requests. The default is [None].
  ///
  /// [T] The type of structured output to request.
  Future<ChatResponse<T>> getResponse<T>(
    ChatOptions? options,
    bool? useJsonSchemaResponseFormat,
    CancellationToken cancellationToken, {
    Iterable<ChatMessage>? messages,
    String? chatMessage,
    JsonSerializerOptions? serializerOptions,
  }) async {
    // TODO(ai): implement dispatch
    throw UnimplementedError();
  }
}
