name: dart_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.2

dependencies:
  extensions:
    path: ../../packages/extensions
  uuid: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
