name: dart_example
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  extensions:
    path: ../../packages/extensions
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
