import 'chat_client_metadata.dart';
import 'chat_message.dart';
import 'chat_options.dart';
import 'chat_response_update.dart';

/// Represents a chat client.
///
/// Remarks: Applications must consider risks such as prompt injection
/// attacks, data sizes, and the number of messages sent to the underlying
/// provider or returned from it. Unless a specific [ChatClient]
/// implementation explicitly documents safeguards for these concerns, the
/// application is expected to implement appropriate protections. Unless
/// otherwise specified, all members of [ChatClient] are thread-safe for
/// concurrent use. It is expected that all implementations of [ChatClient]
/// support being used by multiple requests concurrently. Instances must not
/// be disposed of while the instance is still in use. However,
/// implementations of [ChatClient] might mutate the arguments supplied to
/// [CancellationToken)] and [CancellationToken)], such as by configuring the
/// options instance. Thus, consumers of the interface either should avoid
/// using shared instances of these arguments for concurrent invocations or
/// should otherwise ensure by construction that no [ChatClient] instances are
/// used which might employ such mutation. For example, the ConfigureOptions
/// method is provided with a callback that could mutate the supplied options
/// argument, and that should be avoided if using a singleton options
/// instance.
abstract class ChatClient implements Disposable {
  /// Sends chat messages and returns the response.
  ///
  /// Returns: The response messages generated by the client.
  ///
  /// [messages] The sequence of chat messages to send.
  ///
  /// [options] The chat options with which to configure the request.
  ///
  /// [cancellationToken] The [CancellationToken] to monitor for cancellation
  /// requests. The default is [None].
  Future<ChatResponse> getResponse(
    Iterable<ChatMessage> messages, {
    ChatOptions? options,
    CancellationToken? cancellationToken,
  });

  /// Sends chat messages and streams the response.
  ///
  /// Returns: The response messages generated by the client.
  ///
  /// [messages] The sequence of chat messages to send.
  ///
  /// [options] The chat options with which to configure the request.
  ///
  /// [cancellationToken] The [CancellationToken] to monitor for cancellation
  /// requests. The default is [None].
  Stream<ChatResponseUpdate> getStreamingResponse(
    Iterable<ChatMessage> messages, {
    ChatOptions? options,
    CancellationToken? cancellationToken,
  });

  /// Asks the [ChatClient] for an object of the specified type `serviceType`.
  ///
  /// Remarks: The purpose of this method is to allow for the retrieval of
  /// strongly typed services that might be provided by the [ChatClient],
  /// including itself or any services it might be wrapping. For example, to
  /// access the [ChatClientMetadata] for the instance, [Object)] may be used to
  /// request it.
  ///
  /// Returns: The found object, otherwise `null`.
  ///
  /// [serviceType] The type of object being requested.
  ///
  /// [serviceKey] An optional key that can be used to help identify the target
  /// service.
  Object? getService(Type serviceType, {Object? serviceKey});
}
