import 'chat_client.dart';
import 'chat_message.dart';
import 'chat_options.dart';
import 'chat_response_update.dart';
import 'chat_role.dart';

/// Provides a collection of static methods for extending [ChatClient]
/// instances.
extension ChatClientExtensions on ChatClient {
  /// Asks the [ChatClient] for an object of type `TService`.
///
/// Remarks: The purpose of this method is to allow for the retrieval of
/// strongly typed services that may be provided by the [ChatClient],
/// including itself or any services it might be wrapping.
///
/// Returns: The found object, otherwise `null`.
///
/// [client] The client.
///
/// [serviceKey] An optional key that can be used to help identify the target
/// service.
///
/// [TService] The type of the object to be retrieved.
TService? getService<TService>({Object? serviceKey}) {
_ = Throw.ifNull(client);
return client.getService(typeof(TService), serviceKey) is TService service ? service : default;
 }
/// Asks the [ChatClient] for an object of the specified type `serviceType`
/// and throws an exception if one isn't available.
///
/// Remarks: The purpose of this method is to allow for the retrieval of
/// services that are required to be provided by the [ChatClient], including
/// itself or any services it might be wrapping.
///
/// Returns: The found object.
///
/// [client] The client.
///
/// [serviceType] The type of object being requested.
///
/// [serviceKey] An optional key that can be used to help identify the target
/// service.
Object getRequiredService(Object? serviceKey, {Type? serviceType, }) {
_ = Throw.ifNull(client);
_ = Throw.ifNull(serviceType);
return client.getService(serviceType, serviceKey) ??
            throw Throw.createMissingServiceException(serviceType, serviceKey);
 }
/// Sends a user chat text message and returns the response messages.
///
/// Returns: The response messages generated by the client.
///
/// [client] The chat client.
///
/// [chatMessage] The text content for the chat message to send.
///
/// [options] The chat options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Future<ChatResponse> getResponse(
  ChatOptions? options,
  CancellationToken cancellationToken,
  {String? chatMessage, },
) {
_ = Throw.ifNull(client);
_ = Throw.ifNull(chatMessage);
return client.getResponseAsync(chatMessage(ChatRole.user, chatMessage), options, cancellationToken);
 }
/// Sends a user chat text message and streams the response messages.
///
/// Returns: The response messages generated by the client.
///
/// [client] The chat client.
///
/// [chatMessage] The text content for the chat message to send.
///
/// [options] The chat options to configure the request.
///
/// [cancellationToken] The [CancellationToken] to monitor for cancellation
/// requests. The default is [None].
Stream<ChatResponseUpdate> getStreamingResponse(
  ChatOptions? options,
  CancellationToken cancellationToken,
  {String? chatMessage, },
) {
_ = Throw.ifNull(client);
_ = Throw.ifNull(chatMessage);
return client.getStreamingResponseAsync(
  chatMessage(ChatRole.user, chatMessage),
  options,
  cancellationToken,
);
 }
 }
