import 'realtime_client_message.dart';
import 'realtime_server_message.dart';
import 'realtime_session_options.dart';

/// Represents a real-time session.
///
/// Remarks: This interface provides methods to manage a real-time session and
/// to interact with the real-time model.
abstract class RealtimeClientSession implements AsyncDisposable {
  /// Gets the current session options.
  RealtimeSessionOptions? get options;

  /// Sends a client message to the session.
  ///
  /// Remarks: This method allows for sending client messages to the session at
  /// any time, which can be used to influence the session's behavior or state.
  /// Concurrency note for provider implementers: [CancellationToken)] may be
  /// called concurrently from multiple sources. For example, a caller may
  /// stream audio via [CancellationToken)] on one thread while middleware such
  /// as `FunctionInvokingRealtimeClientSession` calls [CancellationToken)] to
  /// return tool results from within [CancellationToken)] enumeration on
  /// another thread. If the underlying transport (e.g., a WebSocket) does not
  /// support concurrent sends, provider implementations must serialize access —
  /// for example by using a [SemaphoreSlim] — to prevent protocol violations.
  ///
  /// Returns: A task that represents the asynchronous send operation.
  ///
  /// [message] The client message to send.
  ///
  /// [cancellationToken] A token to cancel the operation.
  Future send(
    RealtimeClientMessage message, {
    CancellationToken? cancellationToken,
  });

  /// Streams the response from the real-time session.
  ///
  /// Remarks: This method cannot be called multiple times concurrently on the
  /// same session instance.
  ///
  /// Returns: The response messages generated by the session.
  ///
  /// [cancellationToken] A token to cancel the operation.
  Stream<RealtimeServerMessage> getStreamingResponse({
    CancellationToken? cancellationToken,
  });

  /// Asks the [RealtimeClientSession] for an object of the specified type
  /// `serviceType`.
  ///
  /// Remarks: The purpose of this method is to allow for the retrieval of
  /// strongly typed services that might be provided by the
  /// [RealtimeClientSession], including itself or any services it might be
  /// wrapping.
  ///
  /// Returns: The found object, otherwise `null`.
  ///
  /// [serviceType] The type of object being requested.
  ///
  /// [serviceKey] An optional key that can be used to help identify the target
  /// service.
  Object? getService(Type serviceType, {Object? serviceKey});
}
