import 'package:extensions/vector_data.dart';
import 'package:test/test.dart';

void main() {
  group('VectorStoreKeyAttribute', () {
    test('defaults to null storageName and isAutoGenerated', () {
      const attr = VectorStoreKeyAttribute();

      expect(attr.storageName, isNull);
      expect(attr.isAutoGenerated, isNull);
    });

    test('accepts storageName and isAutoGenerated', () {
      const attr = VectorStoreKeyAttribute(
        storageName: 'hotel_id',
        isAutoGenerated: true,
      );

      expect(attr.storageName, equals('hotel_id'));
      expect(attr.isAutoGenerated, isTrue);
    });

    test('is const-constructible', () {
      const a1 = VectorStoreKeyAttribute(storageName: 'id');
      const a2 = VectorStoreKeyAttribute(storageName: 'id');

      expect(identical(a1, a2), isTrue);
    });
  });

  group('VectorStoreDataAttribute', () {
    test('defaults: isIndexed and isFullTextIndexed are false', () {
      const attr = VectorStoreDataAttribute();

      expect(attr.storageName, isNull);
      expect(attr.isIndexed, isFalse);
      expect(attr.isFullTextIndexed, isFalse);
    });

    test('accepts all parameters', () {
      const attr = VectorStoreDataAttribute(
        storageName: 'hotel_description',
        isIndexed: true,
        isFullTextIndexed: true,
      );

      expect(attr.storageName, equals('hotel_description'));
      expect(attr.isIndexed, isTrue);
      expect(attr.isFullTextIndexed, isTrue);
    });

    test('is const-constructible', () {
      const a1 = VectorStoreDataAttribute(isIndexed: true);
      const a2 = VectorStoreDataAttribute(isIndexed: true);

      expect(identical(a1, a2), isTrue);
    });
  });

  group('VectorStoreVectorAttribute', () {
    test('requires dimensions', () {
      const attr = VectorStoreVectorAttribute(dimensions: 1536);

      expect(attr.dimensions, equals(1536));
    });

    test('optional fields default to null', () {
      const attr = VectorStoreVectorAttribute(dimensions: 768);

      expect(attr.storageName, isNull);
      expect(attr.indexKind, isNull);
      expect(attr.distanceFunction, isNull);
    });

    test('accepts all parameters', () {
      const attr = VectorStoreVectorAttribute(
        dimensions: 512,
        storageName: 'vec',
        indexKind: IndexKind.hnsw,
        distanceFunction: DistanceFunction.cosineSimilarity,
      );

      expect(attr.dimensions, equals(512));
      expect(attr.storageName, equals('vec'));
      expect(attr.indexKind, equals(IndexKind.hnsw));
      expect(attr.distanceFunction, equals(DistanceFunction.cosineSimilarity));
    });

    test('is const-constructible', () {
      const a1 = VectorStoreVectorAttribute(dimensions: 128);
      const a2 = VectorStoreVectorAttribute(dimensions: 128);

      expect(identical(a1, a2), isTrue);
    });
  });
}
