name: extensions_flutter_firebase
description: Adds firebase to a flutter host.
version: 0.0.1
repository: https://www.github.com/jamiewest/extensions
issue_tracker: https://github.com/jamiewest/extensions/issues?q=is%3Aissue+is%3Aopen+label%3Aextensions-flutter-firebase

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extensions_flutter: ^0.3.6
  firebase_crashlytics: ^2.8.9
  firebase_analytics: ^9.3.3
  firebase_core: ^1.21.1
  firebase_performance: ^0.8.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: